imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: 4 } #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      addthis_pubid : %addthis_pubid%
      ganalytics_id : %ganalytics_id%
      fb_admins     : %fb_admins%
      plusPageUrl   : %plusPageurl%
      baseurl       : %baseurl%
      addthisevent  : %addthisevent%
      user_session  : @user_session
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ClassCentralSiteBundle ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
  search:
    class: SphinxClient
    calls:
      - [SetArrayResult,[true]]
      - [SetLimits, [0,500,1000]]
  dom_parser:
    class: SimplehtmldomClient
  doctrine_cache:
    class: Doctrine\Common\Cache\ApcCache
  cache:
    class: ClassCentral\SiteBundle\Services\Cache
    calls:
      - [setCache,[ @doctrine_cache ] ]
      - [setCacheKeyPrefix, [%baseurl%] ]
  mailgun:
    class: ClassCentral\SiteBundle\Services\Mailgun
    calls:
      - [setApiKey,[%mailgun_api_key%]]
      - [setDomain,[%mailgun_domain_name%]]
  newsletter:
    class: ClassCentral\SiteBundle\Services\Newsletter
    arguments: ['%mailgun_api_key%', '%mailgun_domain_name%']
  user_session:
    class: ClassCentral\SiteBundle\Services\UserSession
    arguments: ['@security.context', '@doctrine', '@session']
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
  user_service:
    class: ClassCentral\SiteBundle\Services\User
    arguments: ['@service_container']
  verification_token:
    class: ClassCentral\SiteBundle\Services\VerificationToken
    arguments: ['@doctrine']
