#ClassCentralStaticBundle:
#    resource: "@ClassCentralStaticBundle/Resources/config/routing.yml"
#    prefix:   /

ClassCentralSiteBundle:
    resource: "@ClassCentralSiteBundle/Resources/config/routing.yml"
    prefix: /
     
BCCResqueBundle:
  resource: "@BCCResqueBundle/Resources/config/routing.xml"
  prefix:   /admin/resque
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
