ClassCentralSiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ClassCentralSiteBundle:Default:index }

ClassCentralSiteBundle_faq:
    pattern:  /faq
    defaults: { _controller: ClassCentralSiteBundle:Default:faq }

ClassCentralSiteBundle_courses:
    pattern:  /courses/{type}
    defaults: { _controller: ClassCentralSiteBundle:Default:courses }

ClassCentralSiteBundle_initiative_novoed:
    pattern:  /initiative/vlab
    defaults:
          _controller: FrameworkBundle:Redirect:redirect
          route: ClassCentralSiteBundle_initiative
          permanent: true # this is for 301
          type: novoed

ClassCentralSiteBundle_initiative:
    pattern:  /provider/{type}
    defaults: { _controller: ClassCentralSiteBundle:Default:initiative }

ClassCentralSiteBundle_initiative_redirect:
  pattern: /initiative/{type}
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: ClassCentralSiteBundle_initiative
    permanent: true

ClassCentralSiteBundle_university:
    pattern:  /university/{slug}
    defaults: { _controller: ClassCentralSiteBundle:Institution:view }    

ClassCentralSiteBundle_institution:
    pattern:  /institution/{slug}
    defaults: { _controller: ClassCentralSiteBundle:Institution:view }

# redirect /stream to /subject
ClassCentralSiteBundle_stream_redirect:
    pattern:  /stream/{slug}
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: ClassCentralSiteBundle_stream
      permanent: true # this is for 301

ClassCentralSiteBundle_stream:
    pattern:  /subject/{slug}
    defaults: { _controller: ClassCentralSiteBundle:Stream:view }  
        
ClassCentralSiteBundle_search:
  pattern: /search
  defaults: { _controller: ClassCentralSiteBundle:Search:index}

ClassCentralSiteBundle_mooc_share:
  pattern: /mooc/{id}/share
  defaults: { _controller: ClassCentralSiteBundle:Course:share}

ClassCentralSiteBundle_mooc:
  pattern: /mooc/{id}/{slug}
  defaults: { _controller: ClassCentralSiteBundle:Course:mooc}

ClassCentralSiteBundle_news:
  pattern: /news
  defaults: {_controller: ClassCentralSiteBundle:News:home}
  
ClassCentralSiteBundle_admin:
    resource: "@ClassCentralSiteBundle/Resources/config/routing_admin.yml"
    prefix: /admin    

subjects:
   pattern: /subjects
   defaults: { _controller: ClassCentralSiteBundle:Stream:subjects}
login:
  pattern: /login
  defaults: {_controller: ClassCentralSiteBundle:Login:login }
  schemes:  [https]

login_check:
  pattern: /login_check
  schemes:  [https]

logout:
  path: /logout
  schemes:  [https]

signup:
  pattern: /signup
  defaults: {_controller: ClassCentralSiteBundle:User:signup }
  schemes:  [https]

signup_mooc:
  pattern: /signup/mooc/{courseId}
  defaults: {_controller: ClassCentralSiteBundle:User:signupMooc }
  schemes:  [https]

signup_search_term:
  pattern: /signup/q/{searchTerm}
  defaults: {_controller: ClassCentralSiteBundle:User:signupSearchTerm }
  schemes:  [https]


signup_create_user:
  pattern: /create_user
  defaults: {_controller: ClassCentralSiteBundle:User:createUser}
  methods: [POST]

forgotpassword:
  pattern: /forgotpassword
  defaults: {_controller: ClassCentralSiteBundle:User:forgotPassword}

forgotpassword_sendemail:
  pattern: /forgotpasswordSendEmail
  defaults: {_controller: ClassCentralSiteBundle:User:forgotPasswordSendEmail}
  methods: [POST]

resetPassword:
  pattern: /resetPassword/{token}
  defaults: {_controller: ClassCentralSiteBundle:User:resetPassword }

resetPassword_save:
  pattern: /resetPassword
  defaults: {_controller: ClassCentralSiteBundle:User:resetPasswordSave }
  methods: [POST]

email_verify:
  pattern: /verify/{token}
  defaults: {_controller: ClassCentralSiteBundle:User:verifyEmail}

#mooc tracker
mooctracker:
  pattern: /mooc-tracker
  defaults: { _controller: ClassCentralSiteBundle:User:moocTracker}

mooctracker_signup:
  pattern: /mooc-tracker-signup
  defaults: { _controller: ClassCentralSiteBundle:User:signUp}

mooctracker_add_course:
  pattern: /user/tracker/course/{courseId}
  defaults: {_controller: ClassCentralSiteBundle:User:addCourseToMOOCTracker }

mooctracker_add_search_term:
  pattern: /user/tracker/searchTerm/{searchTerm}
  defaults: {_controller: ClassCentralSiteBundle:User:addSearchTermToMOOCTracker }

#newsletter
newsletter_subscribe:
  pattern: /newsletters/subscribe/{code}
  defaults: {_controller: ClassCentralSiteBundle:Newsletter:subscribe}

newsletter_subscribe_to:
  pattern: /newsletters/subscribeTo/{code}
  defaults: {_controller: ClassCentralSiteBundle:Newsletter:subscribeTo}

newsletter_subscribed:
  pattern: /newsletters/subscribed/
  defaults: {_controller: ClassCentralSiteBundle:Newsletter:subscribed}
newsletter_mooc_tracker_signup:
  pattern: /newsletters/mooc-tracker-save-user
  defaults: {_controller: ClassCentralSiteBundle:Newsletter:moocTrackerSignup}

#library course routes
user_course_add:
  pattern: /user/course/add
  defaults: {_controller: ClassCentralSiteBundle:User:addCourse}

user_course_remove:
  pattern: /user/course/remove
  defaults: {_controller: ClassCentralSiteBundle:User:removeCourse}

user_library:
  pattern: /user/profile
  defaults: {_controller: ClassCentralSiteBundle:User:library }