ClassCentral\SiteBundle\Entity\SchedulerLog:
    type: entity
    repositoryClass: ClassCentral\SiteBundle\Repository\SchedulerLogRepository
    table: mt_scheduler_logs
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        created:
            type: datetime
            nullable: false
        type:
            type: integer
            unsigned: false
            nullable: false
        emailSent:
            type: boolean
            nullable: true
            column: email_sent
        status:
            type: integer
            unsigned: false
            nullable: false
        jobId:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: job_id
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
